//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jan24Console
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int empId { get; set; }
        public string empName { get; set; }
        public Nullable<double> salary { get; set; }
        public string city { get; set; }
        public int SysNum { get; set; }
    }
}
